/* This file was generated by EclipseMemstructGen.py*/

#ifndef TELEMETRY_MEMSTRUCT_H_
#define TELEMETRY_MEMSTRUCT_H_

#include <vector>
#include <algorithm>
#include <array>
#include <string_view>
using namespace std::literals::string_view_literals;

#define CANFRM_EXTENDED_ID  (1<<29)
#define CANFRM_RTR          (1<<30)

#define MAX_SIG_CNT 8

#define L_ENDIAN 0
#define B_ENDIAN 1

enum DATA_TYPE
{
        TYPE_FLOATING = 0x10,
                TYPE_float,
                TYPE_double,
        TYPE_UNSIGNED = 0x20,
                TYPE_uint32_t,
                TYPE_uint16_t,
                TYPE_uint8_t,
        TYPE_SIGNED = 0x40,
                TYPE_int32_t,
                TYPE_int16_t,
                TYPE_int8_t
};

/*Board enum*/
enum{
        ID_OFFSET_MARIO = 0x100
};

/*Message enum*/
enum CAN_ID
{
/**********************************************************************/
/*                               MARIO                                */
/**********************************************************************/
        M_WATHER_STATION = 1+ID_OFFSET_MARIO,
        M_WHEEL_RPM,
        M_FUTEK,
        M_LOADCELL,
        M_PITCH,
        M_MOTOR_MODES,
        M_MARIO_CAN_INFO,
        M_POWER,
        M_ROPS,
        M_TELEMETRY,
        M_PITCH_AUTO = 12+ID_OFFSET_MARIO
};

/*Signal enum*/
enum SIGNAL_ID
{
/**********************************************************************/
/*                               MARIO                                */
/**********************************************************************/
        S_WIND_SPEED,
        S_WIND_DIRECTION,
        S_WHEEL_RPM,
        S_VEHICLE_SPEED,
        S_ROTOR_RPM,
        S_TORQUE,
        S_LOADCELL,
        S_PITCH_VALUE,
        S_PITCH_ANGLE,
        S_PITCH_MODE,
        S_MAST_MODE,
        S_CAN_REC,
        S_CAN_TEC,
        S_CAN_LEC,
        S_CAN_BOFF,
        S_CAN_ERROR_PASSIVE,
        S_CAN_ERROR_WARNING,
        S_POWER,
        S_TSR,
        S_ROPS,
        S_RSSI,
        S_SNR,
        S_PITCH_TARGET,
        S_PITCH_ROPS,

        NUM_SIGNAL_IDS
};

 /*  SignalDecode struct  */
struct SignalDecode
{
        uint32_t id;
        std::string_view name;
        DATA_TYPE type;
        uint32_t byte_pos;
        uint32_t size;
        uint8_t endianness;
        float multiplier;
};

 /*  MessageDecode struct  */
struct MessageDecode
{
        uint32_t id;
        uint32_t pos;
        std::string_view name;
        uint32_t num_signals;
        SignalDecode signals[MAX_SIG_CNT];  /* Signals */
};

static constexpr std::array<std::pair<uint32_t, MessageDecode>, 11> CAN_MESSAGES 
{{
/**********************************************************************/
/*                               MARIO                                */
/**********************************************************************/
        {
                M_WATHER_STATION, /* CAN-Identifier */
                {
                        M_WATHER_STATION, /* CAN-Identifier */
                        sizeof(float) + sizeof(float), /* DLC of Message */
                        "M_WATHER_STATION", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_WIND_SPEED,   /* Signal ID */
                                        "S_WIND_SPEED",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_WIND_DIRECTION,   /* Signal ID */
                                        "S_WIND_DIRECTION",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0 + sizeof(float),   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_WHEEL_RPM, /* CAN-Identifier */
                {
                        M_WHEEL_RPM, /* CAN-Identifier */
                        sizeof(float) + sizeof(float), /* DLC of Message */
                        "M_WHEEL_RPM", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_WHEEL_RPM,   /* Signal ID */
                                        "S_WHEEL_RPM",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_VEHICLE_SPEED,   /* Signal ID */
                                        "S_VEHICLE_SPEED",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0 + sizeof(float),   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_FUTEK, /* CAN-Identifier */
                {
                        M_FUTEK, /* CAN-Identifier */
                        sizeof(float) + sizeof(float), /* DLC of Message */
                        "M_FUTEK", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_ROTOR_RPM,   /* Signal ID */
                                        "S_ROTOR_RPM",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_TORQUE,   /* Signal ID */
                                        "S_TORQUE",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0 + sizeof(float),   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_LOADCELL, /* CAN-Identifier */
                {
                        M_LOADCELL, /* CAN-Identifier */
                        sizeof(float), /* DLC of Message */
                        "M_LOADCELL", /* Name of Message */
                        1, /* No. of Links */
                        {
                                {
                                        S_LOADCELL,   /* Signal ID */
                                        "S_LOADCELL",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_PITCH, /* CAN-Identifier */
                {
                        M_PITCH, /* CAN-Identifier */
                        sizeof(float) + sizeof(float), /* DLC of Message */
                        "M_PITCH", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_PITCH_VALUE,   /* Signal ID */
                                        "S_PITCH_VALUE",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_PITCH_ANGLE,   /* Signal ID */
                                        "S_PITCH_ANGLE",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0 + sizeof(float),   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_MOTOR_MODES, /* CAN-Identifier */
                {
                        M_MOTOR_MODES, /* CAN-Identifier */
                        sizeof(int32_t) + sizeof(int32_t), /* DLC of Message */
                        "M_MOTOR_MODES", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_PITCH_MODE,   /* Signal ID */
                                        "S_PITCH_MODE",   /* Signal Name */
                                        TYPE_int32_t,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(int32_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_MAST_MODE,   /* Signal ID */
                                        "S_MAST_MODE",   /* Signal Name */
                                        TYPE_int32_t,   /* Signal Type */
                                        0 + sizeof(int32_t),   /* Byte Position */
                                        sizeof(int32_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_MARIO_CAN_INFO, /* CAN-Identifier */
                {
                        M_MARIO_CAN_INFO, /* CAN-Identifier */
                        sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t), /* DLC of Message */
                        "M_MARIO_CAN_INFO", /* Name of Message */
                        6, /* No. of Links */
                        {
                                {
                                        S_CAN_REC,   /* Signal ID */
                                        "S_CAN_REC",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_CAN_TEC,   /* Signal ID */
                                        "S_CAN_TEC",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0 + sizeof(uint8_t),   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_CAN_LEC,   /* Signal ID */
                                        "S_CAN_LEC",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0 + sizeof(uint8_t) + sizeof(uint8_t),   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_CAN_BOFF,   /* Signal ID */
                                        "S_CAN_BOFF",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0 + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t),   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_CAN_ERROR_PASSIVE,   /* Signal ID */
                                        "S_CAN_ERROR_PASSIVE",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0 + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t),   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_CAN_ERROR_WARNING,   /* Signal ID */
                                        "S_CAN_ERROR_WARNING",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0 + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t) + sizeof(uint8_t),   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_POWER, /* CAN-Identifier */
                {
                        M_POWER, /* CAN-Identifier */
                        sizeof(float) + sizeof(float), /* DLC of Message */
                        "M_POWER", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_POWER,   /* Signal ID */
                                        "S_POWER",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_TSR,   /* Signal ID */
                                        "S_TSR",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0 + sizeof(float),   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_ROPS, /* CAN-Identifier */
                {
                        M_ROPS, /* CAN-Identifier */
                        sizeof(uint8_t), /* DLC of Message */
                        "M_ROPS", /* Name of Message */
                        1, /* No. of Links */
                        {
                                {
                                        S_ROPS,   /* Signal ID */
                                        "S_ROPS",   /* Signal Name */
                                        TYPE_uint8_t,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(uint8_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_TELEMETRY, /* CAN-Identifier */
                {
                        M_TELEMETRY, /* CAN-Identifier */
                        sizeof(int32_t) + sizeof(int32_t), /* DLC of Message */
                        "M_TELEMETRY", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_RSSI,   /* Signal ID */
                                        "S_RSSI",   /* Signal Name */
                                        TYPE_int32_t,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(int32_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_SNR,   /* Signal ID */
                                        "S_SNR",   /* Signal Name */
                                        TYPE_int32_t,   /* Signal Type */
                                        0 + sizeof(int32_t),   /* Byte Position */
                                        sizeof(int32_t),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        },
        {
                M_PITCH_AUTO, /* CAN-Identifier */
                {
                        M_PITCH_AUTO, /* CAN-Identifier */
                        sizeof(float) + sizeof(float), /* DLC of Message */
                        "M_PITCH_AUTO", /* Name of Message */
                        2, /* No. of Links */
                        {
                                {
                                        S_PITCH_TARGET,   /* Signal ID */
                                        "S_PITCH_TARGET",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0,   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                },
                                {
                                        S_PITCH_ROPS,   /* Signal ID */
                                        "S_PITCH_ROPS",   /* Signal Name */
                                        TYPE_float,   /* Signal Type */
                                        0 + sizeof(float),   /* Byte Position */
                                        sizeof(float),   /* sizeof */
                                        L_ENDIAN,   /* Endianness */
                                        1.0f,   /* Multiplier */
                                }
                        }
                }
        }
}};


#endif
